set_property IOSTANDARD LVCMOS33 [get_ports BTN0]
set_property IOSTANDARD LVCMOS33 [get_ports LD0]
set_property PACKAGE_PIN U18 [get_ports BTN0]
set_property PACKAGE_PIN U16 [get_ports LD0]

set_property IOSTANDARD LVCMOS33 [get_ports {SEG[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[0]}]
set_property PACKAGE_PIN W4 [get_ports {SEG[11]}]
set_property PACKAGE_PIN V4 [get_ports {SEG[10]}]
set_property PACKAGE_PIN U4 [get_ports {SEG[9]}]
set_property PACKAGE_PIN U2 [get_ports {SEG[8]}]
set_property PACKAGE_PIN V7 [get_ports {SEG[7]}]
set_property PACKAGE_PIN U7 [get_ports {SEG[6]}]
set_property PACKAGE_PIN V5 [get_ports {SEG[5]}]
set_property PACKAGE_PIN U5 [get_ports {SEG[4]}]
set_property PACKAGE_PIN V8 [get_ports {SEG[3]}]
set_property PACKAGE_PIN U8 [get_ports {SEG[2]}]
set_property PACKAGE_PIN W6 [get_ports {SEG[1]}]
set_property PACKAGE_PIN W7 [get_ports {SEG[0]}]
set_property PACKAGE_PIN W17 [get_ports {SW[3]}]
set_property PACKAGE_PIN W16 [get_ports {SW[2]}]
set_property PACKAGE_PIN V16 [get_ports {SW[1]}]
set_property PACKAGE_PIN V17 [get_ports {SW[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN W5 [get_ports CLK]


set_property IOSTANDARD LVCMOS33 [get_ports {DIR[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIR[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NUM[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NUM[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NUM[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NUM[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NUM[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NUM[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NUM[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NUM[0]}]
set_property PACKAGE_PIN W17 [get_ports {NUM[3]}]
set_property PACKAGE_PIN W16 [get_ports {NUM[2]}]
set_property PACKAGE_PIN V16 [get_ports {NUM[1]}]
set_property PACKAGE_PIN V17 [get_ports {NUM[0]}]
set_property PACKAGE_PIN R2 [get_ports {DIR[1]}]
set_property PACKAGE_PIN T1 [get_ports {DIR[0]}]
set_property PACKAGE_PIN W15 [get_ports {NUM[4]}]
set_property PACKAGE_PIN V15 [get_ports {NUM[5]}]
set_property PACKAGE_PIN W14 [get_ports {NUM[6]}]
set_property PACKAGE_PIN W13 [get_ports {NUM[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ddataout[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports out]
set_property PACKAGE_PIN L1 [get_ports out]

set_property BITSTREAM.GENERAL.UNCONSTRAINEDPINS Allow [current_design]

connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]

set_property IOSTANDARD LVCMOS33 [get_ports clkin]
set_property PACKAGE_PIN W5 [get_ports clkin]


set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN U18 [get_ports rst_n]
set_property MARK_DEBUG false [get_nets clk_reg_n_0]




set_property IOSTANDARD LVCMOS33 [get_ports trigger]
connect_debug_port u_ila_0/clk [get_nets [list clkin_IBUF_BUFG]]
connect_debug_port u_ila_0/probe1 [get_nets [list clkin_IBUF_BUFG]]
connect_debug_port dbg_hub/clk [get_nets clkin_IBUF_BUFG]


connect_debug_port u_ila_0/probe1 [get_nets [list rst_out_OBUF]]
set_property IOSTANDARD LVCMOS33 [get_ports rst_out]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ddataout_OBUF[0]} {ddataout_OBUF[1]} {ddataout_OBUF[2]} {ddataout_OBUF[3]} {ddataout_OBUF[4]} {ddataout_OBUF[5]} {ddataout_OBUF[6]} {ddataout_OBUF[7]} {ddataout_OBUF[8]} {ddataout_OBUF[9]} {ddataout_OBUF[10]} {ddataout_OBUF[11]} {ddataout_OBUF[12]} {ddataout_OBUF[13]} {ddataout_OBUF[14]} {ddataout_OBUF[15]} {ddataout_OBUF[16]} {ddataout_OBUF[17]} {ddataout_OBUF[18]} {ddataout_OBUF[19]} {ddataout_OBUF[20]} {ddataout_OBUF[21]} {ddataout_OBUF[22]} {ddataout_OBUF[23]} {ddataout_OBUF[24]} {ddataout_OBUF[25]} {ddataout_OBUF[26]} {ddataout_OBUF[27]} {ddataout_OBUF[28]} {ddataout_OBUF[29]} {ddataout_OBUF[30]} {ddataout_OBUF[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list trigger_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
