# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/simple_fpga_test/project_5/project_5.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/simple_fpga_test/project_5/project_5.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/simple_fpga_test/project_5/project_5.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {{C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/simple/def.h}}
set_property file_type "Verilog Header" [get_files {{C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/simple/def.h}}]
read_mem {
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/simple/dmem.dat}
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/simple/imem.dat}
}
read_verilog -library xil_defaultlib {
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/simple/rfile.v}
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/simple/alu.v}
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/simple/mipse.v}
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/simple/imem.v}
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/simple/dmem.v}
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/simple_fpga_test/project_5/project_5.srcs/sources_1/new/source1.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/simple_fpga_test/project_5/project_5.srcs/constrs_1/new/constr.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/simple_fpga_test/project_5/project_5.srcs/constrs_1/new/constr.xdc}}]


synth_design -top fpga_test -part xc7a35tcpg236-1


write_checkpoint -force -noxdef fpga_test.dcp

catch { report_utilization -file fpga_test_utilization_synth.rpt -pb fpga_test_utilization_synth.pb }
