# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/fpga_mips/fpga_mips.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/fpga_mips/fpga_mips.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/fpga_mips/fpga_mips.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {{C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/fpga_mips/fpga_mips.srcs/sources_1/imports/mips0717/def.h}}
set_property file_type "Verilog Header" [get_files {{C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/fpga_mips/fpga_mips.srcs/sources_1/imports/mips0717/def.h}}]
read_mem {
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/fpga_mips/fpga_mips.srcs/sources_1/imports/mips0717/imem.dat}
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/fpga_mips/fpga_mips.srcs/sources_1/imports/mips0717/dmem.dat}
}
read_verilog -library xil_defaultlib {
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/fpga_mips/fpga_mips.srcs/sources_1/imports/mips0717/rfile.v}
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/fpga_mips/fpga_mips.srcs/sources_1/imports/mips0717/alu.v}
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/fpga_mips/fpga_mips.srcs/sources_1/imports/mips0717/mipse.v}
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/fpga_mips/fpga_mips.srcs/sources_1/imports/mips0717/imem.v}
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/fpga_mips/fpga_mips.srcs/sources_1/imports/mips0717/dmem.v}
  {C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/fpga_mips/fpga_mips.srcs/sources_1/imports/mips0717/test_mipse.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/fpga_mips/fpga_mips.srcs/constrs_1/new/mips_constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Shun Kinoshita/Desktop/CompSysArch/hardware/fpga_mips/fpga_mips.srcs/constrs_1/new/mips_constraints.xdc}}]


synth_design -top test_mipse -part xc7a35tcpg236-3


write_checkpoint -force -noxdef test_mipse.dcp

catch { report_utilization -file test_mipse_utilization_synth.rpt -pb test_mipse_utilization_synth.pb }
