set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {daddr[2]} {daddr[3]} {daddr[4]} {daddr[5]} {daddr[6]} {daddr[7]} {daddr[8]} {daddr[9]} {daddr[10]} {daddr[11]} {daddr[12]} {daddr[13]} {daddr[14]} {daddr[15]} {daddr[16]} {daddr[17]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {ddatain[0]} {ddatain[1]} {ddatain[2]} {ddatain[3]} {ddatain[4]} {ddatain[5]} {ddatain[6]} {ddatain[7]} {ddatain[8]} {ddatain[9]} {ddatain[10]} {ddatain[11]} {ddatain[12]} {ddatain[13]} {ddatain[14]} {ddatain[15]} {ddatain[16]} {ddatain[17]} {ddatain[18]} {ddatain[19]} {ddatain[20]} {ddatain[21]} {ddatain[22]} {ddatain[23]} {ddatain[24]} {ddatain[25]} {ddatain[26]} {ddatain[27]} {ddatain[28]} {ddatain[29]} {ddatain[30]} {ddatain[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
